{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: travelo-proxy-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.proxy.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.proxy.nginxConfig | indent 4 }}
{{- end }}
