{{- if .Values.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelo-proxy
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "travelo.name" . }}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "travelo.name" . }}
        app.kubernetes.io/component: proxy
    spec:
      containers:
      - name: proxy
        image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.proxy.service.targetPort }}
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        resources:
          {{- toYaml .Values.proxy.resources | nindent 10 }}
      volumes:
      - name: nginx-config
        configMap:
          name: travelo-proxy-config
{{- end }}
