{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: travelo-proxy
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
  - port: {{ .Values.proxy.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "travelo.name" . }}
    app.kubernetes.io/component: proxy
{{- end }}
