{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: travelo-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "travelo.name" . }}
    app.kubernetes.io/component: frontend
{{- end }}
