{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: travelo-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "travelo.name" . }}
    app.kubernetes.io/component: backend
{{- end }}
